### ISSUE TITLE
Mutes all tabs or cuts off volume

### ISSUE THREAD

**Issue by carnisht** [trmcnvn/chrome-tab-mute#6]
Since yesterday afternoon, anytime I use the Mute Tab extension, it cuts off the volume on ALL of my tabs. I'm running multiple Google Meet groups in breakout rooms for my students, and on Monday and Tuesday, the mute tab extension worked well to silence the rooms one at a time. Then, yesterday afternoon and this morning when I went to use it, it would shut down the audio in all of my Google Meets, not just one. It then became that even when "unmuted", all of my audio was gone and I could no longer hear anything my students said. The only solution was restarting my computer. I hope this issue can be fixed because I _really_ liked this extension.

**Comment by carnisht** [comment]
Update: Now when I click it, the tab I'm using isn't even muted.

**Comment by trmcnvn** [comment]
Wasn't able to reproduce this. What version of Chrome?

**Comment by carnisht** [comment]
Chrome 85, the newest one.

**Comment by keysmashes** [comment]
Also reported in #2, fwiw.

I'm the developer of [a similar extension](https://github.com/sersorrel/mute-tab), and I've had several reports of this issue, though likewise I can't reproduce it. I'm tracking the issue in sersorrel/mute-tab#3; based on logs provided by a user, I'm suspicious of a bug in Meet or Chrome.
