### ISSUE TITLE
Stopped working on latest version of Chrome

### ISSUE THREAD

**Issue by danofsatx** [trmcnvn/chrome-tab-mute#9]
Chrome just updated to Version 100.0.4896.127, and the plugin (version 1.4) no longer works. It does not respond to the mouse click to mute the tab.

**Comment by dab198** [comment]
My own experience is that the extension does still work, but the mute button stops responding.

When that happens, I just have to toggle the extension off and back on again to restore functionality. Muted tabs stay muted when the button stops working, so it's not a complete extension crash.

**Comment by Valsisttv** [comment]
I'm on Chrome version 105.0.5195.127 and this issue is still present.

It seems that it's become more frequent lately. 
Hopefully it gets fixed soon.

**Comment by trmcnvn** [comment]
Fixed in upcoming 1.5.
